# Generated by Django 3.1 on 2020-09-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_of_date',
            new_name='date_of_birth',
        ),
    ]
