# Generated by Django 3.1 on 2020-10-06 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_datetimes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateTimes',
            new_name='DateTime',
        ),
    ]
