# Generated by Django 3.0.8 on 2020-08-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.CharField(default='asd', max_length=1000),
            preserve_default=False,
        ),
    ]
